version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install --global lerna
      - lerna bootstrap --concurrency=1 -- --production
      - yum install -y amazon-linux-extras which
      - amazon-linux-extras install java-openjdk11
      - pip install aws-sam-cli --upgrade
  pre_build:
    commands:
    # Discover and run unit tests in the '__tests__' directory
    # - npm run test
    # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
    # - npm prune --production
  build:
    commands:
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      # Use AWS SAM to package the application by using AWS CloudFormation
#      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml

